name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy-staging:
    name: Deploy to Staging
    uses: calebsargeant/semantic-release/.github/workflows/tbd-deploy-cloud-run.yaml@main
    environment: staging
    with:
      image_name: my-app
      service: my-app-staging
      project_id: my-gcp-preprod-project
      region: africa-south1
      gar_image: africa-south1-docker.pkg.dev/my-gcp-preprod-project/my-repo/api
      version_type: prerelease
      prerelease_identifier: rc
      port: '8080'
      cpu: '1'
      memory: '512Mi'
      min_instances: '0'
      max_instances: '5'
      concurrency: '80'
      timeout: '300'
      allow_unauthenticated: false
      service_account: 'my-app@my-gcp-preprod-project.iam.gserviceaccount.com'
      env_vars: 'ENVIRONMENT=staging,PORT=8080'
      gcloud_secrets: 'DATABASE_URL=database-url:latest,SECRET_KEY=django-secret-key:latest'
    secrets: inherit

  deploy-prod:
    name: Deploy to Production
    needs: deploy-staging
    uses: calebsargeant/semantic-release/.github/workflows/tbd-deploy-cloud-run.yaml@main
    environment: production
    with:
      image_name: my-app
      service: my-app-api
      project_id: my-gcp-prod-project
      region: africa-south1
      gar_image: africa-south1-docker.pkg.dev/my-gcp-prod-project/my-repo/api
      version_type: stable
      port: '8080'
      cpu: '2'
      memory: '1Gi'
      min_instances: '1'
      max_instances: '10'
      concurrency: '80'
      timeout: '300'
      allow_unauthenticated: true
      service_account: 'my-app@my-gcp-prod-project.iam.gserviceaccount.com'
      env_vars: 'ENVIRONMENT=prod,PORT=8080'
      gcloud_secrets: 'DATABASE_URL=database-url:latest,SECRET_KEY=django-secret-key:latest'
    secrets: inherit
