name: Release
on:
  push:
    branches: [main]
    paths-ignore: ['**.md', '.gitignore', 'LICENSE', 'CHANGELOG.md']
jobs:
  release:
    uses: calebsargeant/semantic-release/.github/workflows/tbd-release.yaml@v1
    with:
      environment: prod
      environments: '["prod"]'
      prerelease-identifiers: '{}'
      image_name: my-app
    secrets: inherit
