#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path

import yaml


ROOT_DIR = Path(__file__).resolve().parents[1]
ACTION_FILE = ROOT_DIR / "action.yml"
OUTPUT_FILE = ROOT_DIR / "docs/reference/action-inputs-outputs.md"


def normalize_description(value: object | None) -> str:
  if value is None:
    return ""
  lines = [line.rstrip() for line in str(value).strip().splitlines()]
  return "\n".join(lines).strip()


def inline_code(value: object) -> str:
  escaped = str(value).replace("`", "\\`")
  return f"`{escaped}`"


def render_default(value: object | None) -> str:
  if value is None:
    return "_Not set._"
  if isinstance(value, str) and value == "":
    return "`''`"
  return inline_code(value)


def render_value(value: object | None) -> str:
  if value is None:
    return "_Not set._"
  if isinstance(value, str) and value == "":
    return "`''`"
  return inline_code(value)


def render_inputs(inputs: dict[str, dict[str, object]]) -> list[str]:
  lines = ["## Inputs", ""]

  if not inputs:
    lines.extend(["_No inputs defined._", ""])
    return lines

  for input_name, input_spec in inputs.items():
    required = bool(input_spec.get("required", False))
    default = input_spec.get("default")
    description = normalize_description(input_spec.get("description"))

    lines.extend(
      [
        f"### `{input_name}`",
        "",
        f"- Required: `{str(required).lower()}`",
        f"- Default: {render_default(default)}",
        "",
        "Description:",
        "",
      ]
    )

    if description:
      lines.extend(description.splitlines())
    else:
      lines.append("_No description provided._")

    lines.append("")

  return lines


def render_outputs(outputs: dict[str, dict[str, object]]) -> list[str]:
  lines = ["## Outputs", ""]

  if not outputs:
    lines.extend(["_No outputs defined._", ""])
    return lines

  for output_name, output_spec in outputs.items():
    value = output_spec.get("value")
    description = normalize_description(output_spec.get("description"))

    lines.extend(
      [
        f"### `{output_name}`",
        "",
        f"- Value: {render_value(value)}",
        "",
        "Description:",
        "",
      ]
    )

    if description:
      lines.extend(description.splitlines())
    else:
      lines.append("_No description provided._")

    lines.append("")

  return lines


def main() -> None:
  with ACTION_FILE.open(encoding="utf-8") as file:
    action_definition = yaml.safe_load(file) or {}

  inputs = action_definition.get("inputs", {})
  outputs = action_definition.get("outputs", {})

  if not isinstance(inputs, dict):
    raise ValueError("action.yml inputs must be a mapping")
  if not isinstance(outputs, dict):
    raise ValueError("action.yml outputs must be a mapping")

  lines: list[str] = [
    "# Action inputs and outputs",
    "",
    "This page is generated from `action.yml` by `scripts/generate-action-reference.py`.",
    "Do not edit this file manually.",
    "",
    "## Source",
    "",
    "- Action definition: `action.yml`",
    "- Generator script: `scripts/generate-action-reference.py`",
    "",
  ]
  lines.extend(render_inputs(inputs))
  lines.extend(render_outputs(outputs))

  OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
  OUTPUT_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")

  relative_output = OUTPUT_FILE.relative_to(ROOT_DIR)
  print(f"Wrote {relative_output}")


if __name__ == "__main__":
  main()
