name: Release
on:
  push:
    branches: [dev, staging, main]
    paths-ignore: ['**.md', '.gitignore', 'LICENSE', 'CHANGELOG.md']
jobs:
  release:
    uses: calebsargeant/semantic-release/.github/workflows/tbd-release.yaml@v1
    with:
      deployment-model: bbd
      branch-map: '{"dev": "dev", "staging": "staging", "main": "prod"}'
      environments: '["dev", "staging", "prod"]'
      prerelease-identifiers: '{"dev": "dev", "staging": "rc"}'
      image_name: my-app
    secrets: inherit
